---
include:
  - board: nice_nano@2.0.0
    shield: charybdis_left
  - board: nice_nano@2.0.0
    shield: charybdis_right
  - board: nice_nano@2.0.0
    shield: settings_reset
  - board: xiao_ble
    shield: charybdis_dongle
