---
include:
  - board: nice_nano@2.0.0
    shield: charybdis_left
    snippet: zmk-usb-logging
  - board: nice_nano@2.0.0
    shield: charybdis_right
    snippet: zmk-usb-logging
  - board: nice_nano@2.0.0
    shield: settings_reset
  - board: nice_nano@2.0.0
    shield: charybdis_dongle
    snippet: zmk-usb-logging