---
include:
  - board: nice_nano@2.0.0
    shield: charybdis_left
  - board: nice_nano@2.0.0
    shield: charybdis_right
  - board: nice_nano@2.0.0
    shield: settings_reset
  - board: nice_nano@2.0.0
    shield: charybdis_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y